---
- name: Add Nextcloud repo using key from URL
  ansible.builtin.deb822_repository:
    name: nextcloud-devs-ppa
    types: [deb, deb-src]
    uris: "https://ppa.launchpadcontent.net/nextcloud-devs/client/ubuntu"
    suites: ["{{ ansible_distribution_release|lower }}"]
    components: [main]
    signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1FCD77DD0DBEF5699AD2610160EE47FBAD3DD469"
    state: present
    enabled: true

- name: Install agent
  ansible.builtin.package:
    name: nextcloud-client
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
