---

- name: Remove old repository
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    update_cache: true
    state: absent
    mode: 644
  loop:
    - deb http://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0_update/ /

- name: Add nextcloud ppa apt key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 1FCD77DD0DBEF5699AD2610160EE47FBAD3DD469

- name: Add nextcloud PPA repository
  ansible.builtin.apt_repository:
    repo: ppa:nextcloud-devs/client
    state: present
    update_cache: true

- name: Install agent
  ansible.builtin.package:
    name: nextcloud-client
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
