---

- name: Read upstream-release file on Linux mint
  ansible.builtin.slurp:
    src: /etc/upstream-release/lsb-release
  register: lsb_release_raw
  when: ansible_distribution|lower == "linux mint"

- name: Decode and parse DISTRIB_CODENAME from upstream-release file on Linux mint
  ansible.builtin.set_fact:
    real_os_release: >-
      {{ (lsb_release_raw.content | b64decode).splitlines()
         | select('match', '^DISTRIB_CODENAME=')
         | map('regex_replace', '^DISTRIB_CODENAME=', '')
         | list | first | lower }}
  when: ansible_distribution|lower == "linux mint"

- name: Set distribution release on other distributions than linux mint
  ansible.builtin.set_fact:
    real_os_release: "{{ ansible_distribution_release | lower }}"
  when: ansible_distribution|lower != "linux mint"

- name: Add Nextcloud repo using key from URL
  ansible.builtin.deb822_repository:
    name: nextcloud-devs-ppa
    types: [deb, deb-src]
    uris: "https://ppa.launchpadcontent.net/nextcloud-devs/client/ubuntu"
    suites: ["{{ real_os_release }}"]
    components: [main]
    signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1FCD77DD0DBEF5699AD2610160EE47FBAD3DD469"
    state: present
    enabled: true
  become: true
  become_user: root

- name: Install agent
  ansible.builtin.apt:
    name:
      - nextcloud-client
      - nautilus-nextcloud
    state: present
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root
